version: "3"
services:
  mysql:
    build: ${IMAGES_ROOT}/mysql
    container_name: ${PROJECT_NAME}_mysql
    ports:
      - ${PORT_MYSQL}:3306
    volumes:
      - ${IMAGES_ROOT}/mysql/data:/var/lib/mysql/:rw
      - ${IMAGES_ROOT}/mysql/conf.d:/etc/mysql/conf.d/:r
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - tacomall_network
  redis:
    build: ${IMAGES_ROOT}/redis
    container_name: ${PROJECT_NAME}_redis
    ports:
      - ${PORT_REDIS}:6379
    volumes:
      - ${IMAGES_ROOT}/redis/redis.conf:/etc/redis/redis.conf
    networks:
      - tacomall_network
  nginx:
    build: ${IMAGES_ROOT}/nginx
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - ${PORT_NGINX}:80
    volumes:
      - ./admin/dist:/var/www/html/admin
      - ${IMAGES_ROOT}/nginx/etc/nginx/ssl:/etc/nginx/ssl
      - ${IMAGES_ROOT}/nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ${IMAGES_ROOT}/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - tacomall_network
  open:
    build: 
      context: ${IMAGES_ROOT}/open
    environment:
      - SPRING_PROFILE=${SPRING_PROFILE}
    container_name: ${PROJECT_NAME}_open
    ports:
      - ${PORT_OPEN}:4000
    volumes:
      - ./server:/app
    depends_on:
      - mysql
      - redis
    networks:
      - tacomall_network
  admin:
    build: 
      context: ${IMAGES_ROOT}/admin
    environment:
      - SPRING_PROFILE=${SPRING_PROFILE}
    container_name: ${PROJECT_NAME}_admin
    ports:
      - ${PORT_ADMIN}:4001
    volumes:
      - ./admin:/var/www/html
      - ./server:/app
    depends_on:
      - mysql
      - redis
    networks:
      - tacomall_network
  ma:
    build: 
      context: ${IMAGES_ROOT}/ma
    environment:
      - SPRING_PROFILE=${SPRING_PROFILE}
    container_name: ${PROJECT_NAME}_ma
    ports:
      - ${PORT_MA}:4002
    volumes:
      - ./ma:/var/www/html
      - ./server:/app
    depends_on:
      - mysql
      - redis
    networks:
      - tacomall_network
networks:
  tacomall_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24