server:
  port: 4000
spring:
  profiles:
    active: dev

logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.tacomall.common.mapper
  mapper-locations: classpath*:/mapper/**/*Mapper.xml

  configuration:
    call-setters-on-nulls: true